{
    ".logement.sortie.deperdition.deperdition_renouvellement_air": .logement.sortie.deperdition.deperdition_renouvellement_air,
    ".logement.sortie.deperdition.deperdition_enveloppe": .logement.sortie.deperdition.deperdition_enveloppe,
    ".logement.sortie.qualite_isolation.ubat": .logement.sortie.qualite_isolation.ubat,
    ".logement.sortie.apport_et_besoin.surface_sud_equivalente": .logement.sortie.apport_et_besoin.surface_sud_equivalente,
    ".logement.sortie.apport_et_besoin.nadeq": .logement.sortie.apport_et_besoin.nadeq,
    ".logement.sortie.apport_et_besoin.besoin_ecs": .logement.sortie.apport_et_besoin.besoin_ecs,
    ".logement.sortie.apport_et_besoin.besoin_ch": .logement.sortie.apport_et_besoin.besoin_ch,
    ".logement.sortie.ef_conso.conso_ecs": .logement.sortie.ef_conso.conso_ecs,
    ".logement.sortie.ef_conso.conso_ch": .logement.sortie.ef_conso.conso_ch,
    ".logement.sortie.apport_et_besoin.v40_ecs_journalier": .logement.sortie.apport_et_besoin.v40_ecs_journalier,
    ".logement.sortie.emission_ges.emission_ges_5_usages_m2": .logement.sortie.emission_ges.emission_ges_5_usages_m2,
    ".logement.sortie.ep_conso.ep_conso_5_usages_m2": .logement.sortie.ep_conso.ep_conso_5_usages_m2,
    ".logement.sortie.cout.cout_5_usages": .logement.sortie.cout.cout_5_usages,
    # "": .logement.sortie.apport_et_besoin.apport_interne_ch,
    # "": .logement.sortie.apport_et_besoin.apport_solaire_ch,
    # "": .logement.enveloppe.inertie.enum_classe_inertie_id,
    # "": .logement.sortie.confort_ete.enum_indicateur_confort_ete_id,
    # "": .logement.sortie.production_electricite.production_pv,
}
